In [32]:
# Import Pustaka
import os
import cv2
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix
from tqdm import tqdm

# --- Konfigurasi Data ---
# Ganti BASE_DIR dengan jalur ke folder 'dataset' Anda
BASE_DIR = 'dataset/train' 

# Kelas koin yang akan diklasifikasikan (sesuai nama folder)
CLASSES = ['50', '100', '200', '500', '1000']

In [33]:
def extract_hu_moments(image_path):
    """
    Memuat gambar, melakukan pra-pemrosesan, dan mengekstrak Momen Invarian Hu.
    """
    # 1. Muat Gambar dan Konversi ke Grayscale
    img = cv2.imread(image_path)
    if img is None:
        return None
    
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    
    # 2. Pra-pemrosesan dan Segmentasi
    # Gunakan Gaussian Blur untuk mengurangi noise
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    
    # Gunakan Thresholding Adaptif atau Otsu untuk mendapatkan gambar biner
    # Otsu's Thresholding seringkali bagus untuk koin
    _, thresh = cv2.threshold(blur, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    
    # Optional: Erosi/Dilasi untuk membersihkan bintik kecil
    kernel = np.ones((3,3),np.uint8)
    thresh = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)
    
    # 3. Cari Kontur
    # Diasumsikan kontur terbesar adalah koin itu sendiri
    contours, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    if not contours:
        return None
    
    # Ambil kontur terbesar
    largest_contour = max(contours, key=cv2.contourArea)
    
    # 4. Hitung Momen dan Momen Invarian Hu
    moments = cv2.moments(largest_contour)
    hu_moments = cv2.HuMoments(moments).flatten()
    
    # 5. Normalisasi Fitur (Log Transform)
    # Log transform membantu menstabilkan nilai fitur, sering digunakan pada Momen Hu
    # hu_moments_normalized = -np.sign(hu_moments) * np.log10(np.abs(hu_moments))
    epsilon = 1e-12
    hu_moments_normalized = -np.sign(hu_moments) * np.log10(np.abs(hu_moments) + epsilon)

    if np.any(np.isnan(hu_moments_normalized)) or np.any(np.isinf(hu_moments_normalized)):
        return None

    return hu_moments_normalized

# --- Proses Pengumpulan Data ---
features = []
labels = []

print("Memulai pengumpulan dan ekstraksi fitur Momen Hu...")

for i, class_name in enumerate(CLASSES):
    class_path = os.path.join(BASE_DIR, class_name)
    
    if not os.path.isdir(class_path):
        print(f"Peringatan: Folder {class_path} tidak ditemukan. Melewati.")
        continue
        
    # Iterasi melalui setiap gambar di dalam folder kelas
    image_files = [f for f in os.listdir(class_path) if f.endswith(('jpg', 'jpeg', 'png'))]
    
    # Gunakan tqdm untuk menampilkan progress bar
    for filename in tqdm(image_files, desc=f'Memproses {class_name}'):
        image_path = os.path.join(class_path, filename)
        
        hu_features = extract_hu_moments(image_path)
        
        if hu_features is not None:
            features.append(hu_features)
            labels.append(class_name)

print("\nEkstraksi fitur selesai.")
print(f"Total sampel yang diekstrak: {len(features)}")

Memulai pengumpulan dan ekstraksi fitur Momen Hu...


Memproses 1000: 100%|██████████| 28/28 [00:00<00:00, 496.52it/s]


Ekstraksi fitur selesai.
Total sampel yang diekstrak: 140


In [34]:
# Konversi list ke numpy array
X = np.array(features)
y = np.array(labels)

# Bagi data menjadi Training (80%) dan Testing (20%)
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size=0.2, 
                                                    random_state=42, 
                                                    stratify=y) # stratify memastikan pembagian kelas yang merata

print(f"Jumlah sampel pelatihan (Train): {len(X_train)}")
print(f"Jumlah sampel pengujian (Test): {len(X_test)}")

# --- Training Model SVM ---
model = SVC(kernel='rbf', C=10, gamma='scale')
model.fit(X_train, y_train)

print("Training selesai!")

Jumlah sampel pelatihan (Train): 112
Jumlah sampel pengujian (Test): 28
Training selesai!


In [35]:
# --- Prediksi dan Evaluasi ---

# Prediksi pada data pengujian
y_pred = model.predict(X_test)

print("\n--- Laporan Klasifikasi SVM ---")
print(classification_report(y_test, y_pred, target_names=CLASSES))

print("\n--- Confusion Matrix ---")
# Confusion Matrix menunjukkan seberapa banyak prediksi yang benar vs salah per kelas
cm = confusion_matrix(y_test, y_pred, labels=CLASSES)
print(cm)


--- Laporan Klasifikasi SVM ---
              precision    recall  f1-score   support

          50       0.20      0.33      0.25         6
         100       0.00      0.00      0.00         5
         200       0.67      0.67      0.67         6
         500       0.50      0.17      0.25         6
        1000       0.56      1.00      0.71         5

    accuracy                           0.43        28
   macro avg       0.38      0.43      0.38        28
weighted avg       0.39      0.43      0.38        28


--- Confusion Matrix ---
[[1 3 1 1 0]
 [0 2 1 2 1]
 [0 2 4 0 0]
 [0 0 0 5 0]
 [1 3 0 1 0]]


In [36]:
# Import joblib untuk menyimpan model
import joblib

# Simpan model yang sudah dilatih (untuk digunakan nanti)
MODEL_FILENAME = 'svm_coin_classifier.joblib'
joblib.dump(model, MODEL_FILENAME)
print(f"\nModel telah disimpan sebagai: {MODEL_FILENAME}")

# --- Simulasi Klasifikasi Gambar Baru ---

# Anda bisa mengganti ini dengan path gambar koin baru dari user
# new_coin_path = 'path/to/new/user/coin.jpg' 
# Anggap saja kita mengambil salah satu gambar dari set pengujian sebagai contoh:
# Gunakan path gambar koin 500 sebagai contoh (Anda harus mendapatkan path gambar sebenarnya)
# Contoh path:
# example_new_coin_path = os.path.join(BASE_DIR, '500', 'contoh_koin_500.jpg')

# --- Contoh Kode Klasifikasi ---
def classify_new_coin(image_path, trained_model):
    """Melakukan prediksi pada gambar koin baru."""
    
    # 1. Ekstrak fitur
    new_features = extract_hu_moments(image_path)
    
    if new_features is None:
        return "Gagal memproses gambar (kontur tidak ditemukan)."
        
    # 2. Ubah format menjadi array 2D (dibutuhkan oleh Scikit-learn)
    new_features = new_features.reshape(1, -1)
    
    # 3. Prediksi
    prediction = trained_model.predict(new_features)
    
    return prediction[0]

# Memuat model yang disimpan
# loaded_model = joblib.load(MODEL_FILENAME)

# Lakukan prediksi (gunakan model 'model' yang masih ada di memori untuk demo)
# KLASIFIKASI_HASIL = classify_new_coin(example_new_coin_path, model) 
# print(f"\nKoin baru diklasifikasikan sebagai: {KLASIFIKASI_HASIL}")


Model telah disimpan sebagai: svm_coin_classifier.joblib


In [37]:
# --- Lanjutan dari Simulasi Klasifikasi Gambar Baru ---

# Jalur (Path) ke gambar koin baru yang ingin diuji
NEW_COIN_PATH = 'tests/test0.png'

# Pastikan Anda telah menjalankan Cell 13 di mana fungsi classify_new_coin didefinisikan
# dan Cell 11 di mana model dilatih.

print(f"Mencoba mengklasifikasikan gambar: {NEW_COIN_PATH}")

# Panggil fungsi klasifikasi
try:
    # Model 'model' sudah terlatih dan ada di memori (dari Cell 11)
    KLASIFIKASI_HASIL = classify_new_coin(NEW_COIN_PATH, model)
    
    # Cek hasil
    if KLASIFIKASI_HASIL in CLASSES:
        print(f"\n✅ HASIL PREDIKSI: Koin ini diklasifikasikan sebagai **Rp {KLASIFIKASI_HASIL}**")
    else:
         print(f"\n❌ HASIL PREDIKSI: {KLASIFIKASI_HASIL}")
         
except NameError as e:
    print(f"\n[ERROR]: Variabel 'model' atau fungsi 'classify_new_coin' belum didefinisikan. Mohon jalankan Cell 11 (Training) dan Cell 13 (Definisi fungsi) terlebih dahulu. Detail: {e}")
except FileNotFoundError:
    print(f"\n[ERROR]: File tidak ditemukan di jalur: {NEW_COIN_PATH}. Pastikan file tersebut ada.")
except Exception as e:
    print(f"\n[ERROR]: Terjadi kesalahan saat klasifikasi: {e}")

Mencoba mengklasifikasikan gambar: tests/test0.png

✅ HASIL PREDIKSI: Koin ini diklasifikasikan sebagai **Rp 200**
